- hosts: localhost
  vars:
    proxy_env:
      https_proxy: http://172.25.174.30:3128
  tasks:
    - name: install packages
      become: true
      become_user: root
      apt:
        state: present
        name:
           - vim
           - wget
           - net-tools
           - sudo
           - dnsutils
           - htop
           - traceroute
           - tree
           - ncdu
           - bash-completion
           - make
    - name: Create a directory for VIM 
      file:
        path: ~/.vim/colors/
        state: directory
        mode: '0755'
    - name: Download solarized.vim
      environment: "{{ proxy_env }}"
      become: true
      become_user: root
      get_url:
        url: https://raw.github.com/altercation/vim-colors-solarized/master/colors/solarized.vim
        dest: ~/.vim/colors
    - name: Download vimrc
      environment: "{{ proxy_env }}"
      become: true
      become_user: root
      get_url:
        use_proxy: yes 
        url: https://raw.githubusercontent.com/podolyak-rs/main/master/vimrc
        dest: ~/
    - name: Move vimrc to .vimrc
      changed_when: false
      command: mv ~/vimrc ~/.vimrc
